### PR TITLE
Armor balancing

### PR DESCRIPTION
**Pull request by Hekzder**
## About The Pull Request

Balances all of the armor that was recently implemented and changed around as a result of Infra's new sprites. The intended final product for armor balance [can be seen here.](https://docs.google.com/document/d/1NdCD5uE_K3PVuutO3Oj6_pJ_csHCuoLzzoM3ycMNKW8/edit?usp=sharing) 

Generally, compared to what we had before, armor has become a lot more universal, instead of a bunch of different armor values per tier, it's generally been scaled down so that armor is ideally more of a cosmetic choice and exact stats of an armor has minimal impact on whether or not someone will choose it over another, atleast when it comes to armors of the same tier. 

## Why It's Good For The Game

We'll need to balance armor eventually.

### CODE REVIEW

**Comment by Hekzder** [comment]
Draft for now, currently this just begins some initial balancing and cleans up some .dmis and .dm files to purge legacy armors that we aren't going to be using anymore.

**Comment by Mannybrado** [comment]
The only gripe I personally have is the tire armor. It either shouldn't be a tier one, or should be at least better for melee than the other tier ones. You're literally wearing tires; its a bit different than a leather jacket. Maybe its just me, though.

**Comment by ProfessorPopoff** [comment]
I was really hoping that we could take more of a specialization approach to armor balancing, But apparently that isn't your intent at all. 

**Damn.**

**Comment by mrpibb4201337** [comment]
Maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaan that's lame as fuck

**Comment by TheRealScarHomie** [comment]
no soul

**Comment by Mannybrado** [comment]
no soul :trollface:

**Comment by Hekzder** [comment]
Most recent commit finalizes body armor. Helmets will come later, not a ton to do. After that is spawners and then cleaning up to make sure everything compiles and it should be good to go. 

BoS armor balancing will come later down the line and hopefully Infra will be spriting some more helmets for us later as well, otherwise armor should be looking pretty good balance wise.

This most recent commit also included some minor tweaks to tire armor and heavy metal armor.

**Comment by Hekzder** [comment]
The incredibly minimal amount of headgear we have should is now balanced and more fully implemented. Lots of legacy headgear was purged in the process.

**Comment by Hekzder** [comment]
pain and agony

**Comment by Hekzder** [comment]
After immense pain and torment, this now compiles properly. Just needs some light testing and it should be good to go.

**Comment by Hekzder** [comment]
excruciating pain, eternal torment, never ending agony

This is going back to a draft since the suit PR got merged. I need to solve merge conflicts and then I may as well fuck with everything that got added while I'm at it, so this won't be ready again for a while.

**Comment by Hekzder** [comment]
Going to have to start this PR from scratch at another point, other merges have heavily fucked this PR.

**Pull request closed without merging**
