### PR TITLE
Adds map changes

### PR DESCRIPTION
**Pull request by kperdue2002**
Adds changes to Mammoth.dmm

## About The Pull Request

This PR adds two newly finished building interiors to the downtown/main portion of the Mammoth map.
This includes a hip burger joint, the scene of many a sockhop in days of old, only to close due to an untimely accident, and a solo practicing lawyer's office where the aspiring law official met an untimely end shortly before the world itself changed forever.

## Why It's Good For The Game

These two buildings were previously completely empty. These changes fix that and add just a little more flavor to the game world.

### CODE REVIEW

**Comment by kperdue2002** [comment]
I forgot to add images, so here they are.

The diner/dancing parlor
image
image


The lawyer's office
image

**Comment by kperdue2002** [comment]
The lower level
image

**Review by uomo91 — CHANGES_REQUESTED** [review]
This can be merged once you fix your stairs in that basement.

**Comment by kperdue2002** [comment]
I fixed my stairs.
image
:)

**Review by uomo91 — APPROVED** [review]

**Pull request merged**
