### PR TITLE
quirky combat arena

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
Heyyyyy.... Hello.

With a new combat test coming up on the horizon, I took the liberty of stealing the spotlight and remaking the Combat Arena. This version is asymmetric and focused towards simulating the different scenarios people would fight in, all jammed in one 75x65 map. 

image
image
image

### CODE REVIEW

**Comment by Dr-Oreo** [comment]
It's cool, I guess. Could you maybe make it a fort? Perhaps 2Forts

**Comment by Mannybrado** [comment]
Not interested.

**Comment by DarixRexus** [comment]
I'm gonna break from the others here and say this is actually a pretty good indication of what combat will involve, moving across buildings and rooms rather than a perfectly symmetrical space.

**Comment by mrpibb4201337** [comment]
Are you still working on this or is there some other reason it hasn't been merged?

**Comment by ProfessorPopoff** [comment]
I'm not actively adding anything to it currently. Waiting for suggestions/merge

**Comment by mrpibb4201337** [comment]
Maybe add some wrecked cars as cover if you want. Like just a handful. Perhaps to replace some of the sandbags(because they aren't that common)

**Comment by ProfessorPopoff** [comment]
image
image
image

This is the current state of the map. It's been expanded to 100x100 to alleviate the messery that was happening due to it being smaller than Centcom

**Pull request merged**
