### PR TITLE
Various east town Drought changes

### PR DESCRIPTION
**Pull request by Mannybrado**
## About The Pull Request
I started this PR like a few weeks ago so I don't remember all of the changes, however:

- Changes the diner in the northeast part of the town to an outdoor one.

- Some awkwardly small rooms in buildings have been made larger. (like the police station)

- Replaces a lot of different things with new furniture and shelves.

- Various minor fixes like stuff not being pixel shifted or stairs not being placed correctly. 

image
image
probably just going to kill this whole area in a different PR but at least this makes it slightly better

## Why It's Good For The Game
drought

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
Everything looks fine enough. My one gripe is this area. 

image

It's weird to have little bits of area sticking out away from others. Think of it like a powergrid. (It basically is)

If you have a corner of a building blown up, there probably wouldn't be a single foot that's still powered. PROBABLY. Either way so we can avoid any weird stuff going on, this ought to be trimmed. God forbid you climb over a low wall like that and suddenly the background ambiance changes for all of 0.3 seconds.

**Comment by Mannybrado** [comment]
I dunno. I really don't think it matters, on the very very very small chance a player happens to drag something there that's powered.... whatever. I filled it in mostly for consistency and because I don't really think it matters since weather is based on the roofing.

**Comment by ProfessorPopoff** [comment]
> I dunno. I really don't think it matters, on the very very very small chance a player happens to drag something there that's powered.... whatever. I filled it in mostly for consistency and because I don't really think it matters since weather is based on the roofing.
 
If you /really/ wanted it to be consistent, you'd have put the area over the floors and not the low walls. Odd choice there. Regardless, still probably yoink the area off. It doesn't really have a purpose there, and the only thing it will ever do is change the ambiance if you climb over it. Which is pretty dumb.

**Comment by Mannybrado** [comment]
oh, wait. is the screenshot you posted what it looks like on your side?

**Comment by Mannybrado** [comment]
image
this is what I did. idk why its not there for you.

**Comment by ProfessorPopoff** [comment]
> image
> this is what I did. idk why its not there for you.

Don't know. I've got the most recent version. Perhaps you should commit and push.

**Comment by Mannybrado** [comment]
try looking again, i guess

**Pull request merged**
