### PR TITLE
The Chairening

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
Hey hey.... Gotta stop saying that. How else do people open up their PRs?

TODAY I bring you a revolutionary feat. The ability to turn a chair 90 degrees into its side is now HERE. Incredible isn't it? This PR brings fully interactable chairs with in-hands made by the master spriter- myself.

image

Should work good. Tested it, didn't noticed any f-ups.

### CODE REVIEW

**Comment by mrpibb4201337** [comment]
Now we're just holding out for new stool sprites :^(

**Review by Hekzder — APPROVED** [review]
Unless you want to keep this open for adding anything else on, then this is probably fine to merge and will do so later tonight or tomorrow if there are no objections.

**Comment by ProfessorPopoff** [comment]
image

Added the radio to go along with the chairs. I'm done with this PR overall.

**Comment by Hekzder** [comment]
What parts of the code are actually different and needed in comparison to just the base intercom on the ham radio file? It should be trimmed down to some degree, it currently looks like a literal copy + paste of intercom code with some minor changes.

**Comment by Hekzder** [comment]
Going to just merge this for now. The code works even if _a little bit_ messy, potentially. It can be ironed out later down the road, this PR will be useful for mappers ASAP.

**Pull request merged**
