### PR TITLE
Basic overhaul of Mammoth's layout. (Fixed edition)

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
Fucked up my first PR so why not. Re-scrambled the map into something palpable, added a couple of basic layouts to get the idea of a new, filled map. There's currently no trees, spare for a couple lining out a path towards the north-west camp.

image

Basic overview

image
Overhead vibe check

image
Gay lover check

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
Likely going to shift the NCR base to somewhere else. I've got a couple of ideas... NO SPOILERS...

**Comment by Hekzder** [comment]
I'm almost certain you could achieve a similar layout with an expansion of the map, that is actually literally what Oreo was doing before the mapping freeze. The layout looks good and I've always liked it. The expansion does not look good and I have never liked it. Especially given that you expanded the map and then kept the rocky areas the exact same. 

I genuinely don't understand why we can't just cut down on rocky parts of the map and use that new space instead of having to expand the entire map but preserve the rock or even expand it in some places.

**Comment by DarixRexus** [comment]
I had to open up the map file we have now to see what was substantially different. This isn't what I was anticipating when you talked about a large map change. All its really done is increase the amount of deadspace. The map is not finished, and until we finish it I don't see a reason to expand it as significantly as this.

**Comment by ProfessorPopoff** [comment]
Wrapping up the very last bit of it. This is basically what I envisioned it to look like. Overall it's: 
Relatively better laid out
More fruitful, LESS DEADSPACE than previous versions of Mammoth
Filled with plenty of locations to deck out building-wise

The only thing I can't really decide on is where I want the Hotel at, so i put it near the entrance of mammoth with a new quirky little parking lot. 

image


image


image

**Comment by uomo91** [comment]
I'm seeing some mismatches between z-levels on roofs and the like on various buildings, also the bottom floor level of the tribal base didn't get moved over. Some of this seems to have been fixed in your screenshots but it's not in your this PR's most recent commit.

**Comment by ProfessorPopoff** [comment]
image
image
image
There it is fellas. 15600 tile reduction. There you go.

**Pull request merged**
