### PR TITLE
Drought: The lowpop desert shitshow.

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
This PR adds the map "Drought" to our server. It is a low-pop Legion/Town/Ranger map built around having a smaller map with controlled traffic flow to encourage player encounters.

image
image
image

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
image
image

**Comment by ProfessorPopoff** [comment]
The rough idea: 
image

**Review by uomo91 — CHANGES_REQUESTED** [review]
Something went wrong here, DNM until fixed.

**Comment by ProfessorPopoff** [comment]
The screw up has been fixed and i'm putting out there that i'm 100% fine with the current layout. I'll begin work on it again when i've got my days off Friday/Saturday

**Comment by ProfessorPopoff** [comment]
IT'S FIXED.

**Review by uomo91 — APPROVED** [review]
Looks good for now, will review more in depth later.

**Pull request merged**
