### PR TITLE
Super-store sponsored by Manny Mammoth: Electric wuhhhh edition

### PR DESCRIPTION
**Pull request by ProfessorPopoff**
Hey he-

image
image

I've been working on the supermarket a bit. Made it look decent (in my eyes). I'm going to continue to carve it out a bit more, flesh out the top Z a tad bit perhaps. I've got a bit of a start on it already, hopefully making an area on the top of it with a lil' bit of backstory.

As a mini side note I also edited the mechanics across the street to not have a curb in front of the drivein.

### CODE REVIEW

**Comment by Mannybrado** [comment]
yea... looks good. only thing i dont like is this
image
doesnt make sense to have this if there is a checkout area, its not supposed to be a mall. could wall it off and make it only storage.

**Comment by ProfessorPopoff** [comment]
> yea... looks good. only thing i dont like is this
> image
> doesnt make sense to have this if there is a checkout area, its not supposed to be a mall. could wall it off and make it only storage.

Dunno bud. I thought it like it was a help desk. Like most clothing sections of stores have.

**Comment by ProfessorPopoff** [comment]
image
image

Updates the second Z, shuffles around a bit of the stuff on the base Z and adds some more bodies and clutter.

**Comment by mrpibb4201337** [comment]
Nooooooo bro died checkin them bitches out. Fucked up!
image

**Comment by ProfessorPopoff** [comment]
I'm considering adding a potential lower level, but unfortunately there was things beneath it. I've gone ahead and taken the liberty of moving them elsewhere. On top of this, i've stripped the little metro path and kept it sectioned off in the top of the map, with a single terminal. 

image
image

**Comment by ProfessorPopoff** [comment]
Ready for review, GAMERS. I've added ghouls to populate the building, for future use. They're relatively basic.

**Comment by ProfessorPopoff** [comment]
image
image
image

The basement level is a bit basic. Some more of this can be expanded on later, though. Moreso when I have an actual idea what sort of loot should be going down there.

**Pull request merged**
