### PR TITLE
Add some stuff to this building lol

### PR DESCRIPTION
**Pull request by mrpibb4201337**
Makes this building really cool. 😎 
image
image
Also replaces or removes some of the light tubes in the buildings I previously spat map juice on.
image
image
These ones. Too many light tubes previously. Let's hope github doesn't have a heart attack and I don't have a stroke this time.

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
Should probably keep these as a singular type for aesthetic reason. One or the other.
image

Similarly,  This room doesn't need the light tube PLUS the light bulb in that short space. 
image

And finally, I always thought the weird lip things kinda looked odd. You'd probably be better off making it railings, but that's just my personal criticism.
image

**Comment by mrpibb4201337** [comment]
> Should probably keep these as a singular type for aesthetic reason. One or the other.
> image
> 
> Similarly, This room doesn't need the light tube PLUS the light bulb in that short space.
> image
> 
> And finally, I always thought the weird lip things kinda looked odd. You'd probably be better off making it railings, but that's just my personal criticism.
> image

Maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaan I wish you would have said all that when I had the original PR(s) up. Also I always thought the railings were stupid, not every building with a second story has a damn railing. Imagine every building with roof access had railings that would look STUPID. I wish we had like tarred roof floors so I could make it look not as stupid but here we are. I'll make the lights consistent and make sense rq.

**Comment by ProfessorPopoff** [comment]
> > Should probably keep these as a singular type for aesthetic reason. One or the other.
> > image
> > Similarly, This room doesn't need the light tube PLUS the light bulb in that short space.
> > image
> > And finally, I always thought the weird lip things kinda looked odd. You'd probably be better off making it railings, but that's just my personal criticism.
> > image
> 
> Maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaan I wish you would have said all that when I had the original PR(s) up. Also I always thought the railings were stupid, not every building with a second story has a damn railing. Imagine every building with roof access had railings that would look STUPID. I wish we had like tarred roof floors so I could make it look not as stupid but here we are. I'll make the lights consistent and make sense rq.
> Also do you have any thoughts on the building that I actually made this PR to work on????? :) I put the body there like the guy was upstairs at the sandbags next to the hole, the roof got blown out, and he fell backwards down a story.

Yeah I saw it. P cool.  Like I said, If you want to keep the rail replacement like that- I suppose you could. I'm not too keen on limiting artistic choice, as I think it's sort of a fucked thing to do. Each person thinks something looks better and as long as other people don't have a problem with it, I generally don't either. For consistency though you oughta have one type of light in the room. I can't imagine any building would mix them like that, spare for in very generalize spots.

**Comment by mrpibb4201337** [comment]
POV you just had your lights switched
image
image

**Comment by mrpibb4201337** [comment]
Speedmerge 😎

**Comment by ProfessorPopoff** [comment]
This will need to be updated. Get it into the most recent master commit to be up to date with Riddler's changes and i'll merge it.

**Comment by mrpibb4201337** [comment]
K

**Comment by mrpibb4201337** [comment]
Fuck you fuck you fuck you FUCK YOU

**Comment by mrpibb4201337** [comment]
This is probably alright

**Comment by ProfessorPopoff** [comment]
Cool. Merged.

**Pull request merged**
