### PR TITLE
NCR basement fix.

### PR DESCRIPTION
**Pull request by Mannybrado**
the basement of the NCR base is currently not lined up with where its supposed to connect to by a lot. this fixes that.
(((caught original slippin.... dayum,))))))))
No screenshots needed and I already overwrote what it was before.

### CODE REVIEW

**Comment by Mannybrado** [comment]
ok also @originalidea
image
what if i make the center fork into a crossroads, then add a residential area. there's only a single house and 4 apartments for residential in the city. i could make it shittier than the rest of the city so we can still fit some forest in that area.

**Comment by Mannybrado** [comment]
:trollface:

**Comment by ProfessorPopoff** [comment]
I'm currently working on this area, and i've fixed it previously. I thought I had opened a PR for it, Apologies for the confusion. I'd imagine that area can be a wilder-er area with random shit scattered, or potentially a new large location?

I'm making a new dungeon at the very bottom area.

**Comment by Mannybrado** [comment]
honestly, nevermind. the northern area has houses and shit and that works after thinking about it.

**Comment by ProfessorPopoff** [comment]
I am FORMALLY releasing federal grasp of this specific area. I need to figure out exactly what i'm doing with it all, given I don't approve of the building i've made nor the changes, Kinda wack. Have at it if you want.

**Pull request merged**
