### PR TITLE
adds variation to road tiles

### PR DESCRIPTION
**Pull request by Hughgent**
## About The Pull Request

This makes a road tile choose a `dir` (from the cardinal directions) upon initialize. Normally, all road tiles are exactly the same, which leads to a tiling effect.

I also took the liberty of creating the 4 directions from the original tile sprite by rotating the original for each direction.

For someone down the line, this can be moved further up the parent chain (the `dir_variation` var) and put into the regular parent `/turf/open/floor/initialize()`

## Why It's Good For The Game

A little visual stimulation for asphalt ,

image

### CODE REVIEW

**Comment by Hughgent** [comment]
image
it's uh, not so good with the sidewalk tiles.

**Comment by ProfessorPopoff** [comment]
Well... We share opinions about the sidewalks- But I've always wanted our road turfs to have variation- And hey! It looks a lot better now. It looks like a road, instead of just a bunch of cut and paste panels. Nice!

**Comment by infraredbaron** [comment]
Current files are intended to be a place holder once general style is set in stone. Have patience

**Comment by ProfessorPopoff** [comment]
Even if they are, This will be a nice thing to have in the future, IMHO. No matter what way you make it, you'll see patterns if you don't have the turf directions randomized.

**Pull request merged**
