### PR TITLE
[draft] Power Armor: the beginning

### PR DESCRIPTION
**Pull request by ma44**
## About The Pull Request

Introduces a set of dense, stationary power armor that requires people to enter into to wear while allowing for interaction with the outside game world like shooting or picking up stuff.

## Why It's Good For The Game

Power armor as a feature would be nice for the BoS to have

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
based???

**Comment by ma44** [comment]
This will need a redo on some of the power armor helmets because power armor combined is > 32x32 but only 32x32 DMIs are used

**Comment by ma44** [comment]
Same as with thirst, this will be on hold development wise as we figure the philosophy on the role of the power armor and how it is to be balanced

**Comment by ma44** [comment]
Will have to readjust sprites due to pilot's sprite bleeding through

**Comment by ma44** [comment]
Sprites are misaligned from the size of the helmets to the positioning of the eyes. *Pain

**Pull request merged**
