### PR TITLE
Thirst: Mouth Not Wet Edition

### PR DESCRIPTION
**Pull request by ma44**
## About The Pull Request

Adds a component that makes the parent require water to drink or else they experience no side effects as of now, side effects are TBD

## Why It's Good For The Game

Making water an actual resource can be the foundation of an "economy" alongside something that people can fight over for

### CODE REVIEW

**Comment by scarwolff** [comment]
image

modularisation not detected, prepare to be exterminated doughe.

image

**Comment by Hekzder** [comment]
Going to try and boot this up for testing later, seems neat.

**Comment by ma44** [comment]
@scarwolff Modularization added

**Comment by ProfessorPopoff** [comment]
MODULARIZATION. OH GOOOOOOOD

**Comment by ma44** [comment]
This is going on hold until the philosophy on thirst and it's balancing:tm: is to be determined

**Comment by Koshenko** [comment]
Merged this since we can keep it for reference when moving to the new repo.  Commented the base code changes to keep track of them.

**Pull request merged**
