### PR TITLE
Overworked the west side of the map 

### PR DESCRIPTION
**Pull request by Keksk**
Overworked the west side of the map and added smaller buildings over the entire map to fill gaps.

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
Awesome PR, I'd like to personally thank you for helping us out! I'm going to point out a couple things you could potentially touch up in order to get it merge-ready. I may miss a few things myself but i'm certain Uomo is going to look through soon after.

One thing i'd like to specifically point out is to avoid var-editing anything. If you need a different colour item for something you intend on using more than once, you ought to do it code wise or ask someone to, with varying degrees of reliability. We had a bit of a crackdown on this a while back, as it would cause runtimes and slow loading. This was a problem in the older f13s all around. 
image


**WEST SIDE OF THE MAP**

We've got areas that we can use to assign locations for plants to be procedurally placed down. Ranging from light shrubbery and plants to straight dense forests. You can find these at _/area/ms13/snow_
image

image
There's a bit of space tile here. As well as some misplaced area. It looks like you moved that building's first Z level up two tiles, but the top Z's don't align. The upper story also lacks the "Sunnydale" Area. 

image
More or less a non-essential change, but we're trying to use our own assets for the most part. I don't know how far we intend on straying from any /tg/ plants, but we have a wide variety of our own kinds that would fill any potential "roles" some of the /tg/ ones have. 
You can find the seeds for our plants at: _/obj/item/seeds/ms13_
You can find our grown produce at: _/obj/item/food/grown/ms13_

image
We have a raider area in the top right, But I like this smaller localized are for the raiders a lot to be honest. This could be a thing to talk about, and in the event of removing the top right area's buildings in favor of these ones, with slight changes this could be a much better start to a raider base. Our raiders are going to be a single group, unlike previous F13s. 

image
I like the spirit you've got giving off dead bodies. I've taken a liking to making scenes out them. It looks like all the ones you've put down are the base parent of the corpses. We've got our own corpse spawner that'll give out a wastelander appearance. (Will be made a broader selection in the future, as right now they're basic.) You can find our specific wastelander corpses at _obj/effect/mob_spawn/human/corpse/ms13/wastelander_
image

image
Area missed.


**EAST SIDE OF THE MAP**
image
image
Some areas could use touching up around here. 
image
A bit of area messery here. An important thing to note is that we're not really forcing a distinguishing between the cave areas and the mountain areas last I saw. Though it doesn't hurt. I believe Uomo mentioned that he wouldn't mind us just flat out using the mountain area, though you'd have to ask him.

**The UPPER Z level.**
This is an extremely annoying problem, believe me, I know. I've recreated this map at least twenty times like a fool. An important thing to do is to make sure the upper Z level's mountains match up with the lower Z level's. As a general rule of thumb, I usually allow the upper to overhang by one or two tiles max, but can never recede without having a floor turf covering it up. In general, try to make sure a closed turf never has empty space above it. This also goes with making sure that you've got roofs on buildings, as it does matter due to our lighting system and countless other potential factors. 
image
image
image
image

I can't stress enough how much I appreciate you making a mapping PR. I've been on suicide watch for the last 12 months with only manny's shoulder to cry on every once in a while. Uomo will probably swing by with more suggestions, but this is what i've found. The rest of it looks really nice.

**Comment by ProfessorPopoff** [comment]
image
Forgot to mention this is a cool area, It's currently connecting to the backside of the raider area but after seeing that little place you put in the west section, I question if it should even remain the raider area, as i'm liking the thought of the other spot more.
This area is missing room in the bottom Z levels that you'd drop down onto through the open space

**Comment by Keksk** [comment]
I think I fixed every problem mentioned above. I'm not too sure I got them all.
I also added two more buildings to the city and finished the ghoul mining pit,though the ghouls have not been added yet.

**Comment by Mannybrado** [comment]
although this is great and really good............ its really good...........................
i'm kind of not a big fan of MORE mountain areas. this basically kills any chance of a dense forest area at all and i really don't like that. idk. i thought too much rock was an issue before, and this is a fuckload more than that.
basically, get rid of these two areas. caves are shit.
image
image

**Comment by Mannybrado** [comment]
actually, better idea, you could just move those underground.
still though. too much rock.

**Comment by Keksk** [comment]
I moved the cave areas on the second z-level down to the first and exchanged their parts with forest areas + cabins.
Worked on the north section of the map.

**Comment by Keksk** [comment]
Worked on the Z1-Level

**Pull request merged**
