### PR TITLE
Eagle Lakes Mall: Post Nuclear Consumerism

### PR DESCRIPTION
**Pull request by TheRealScarHomie**
## About The Pull Request

Adds in map of "Eagle Lakes Mall" a medium pop giant post-war mall with 4 emergent faction tribes in it. Being slightly smaller than mammoth and sporting up to 6 Z layers this makes it our tallest map yet, a true testament to the Z-Level flexibility we have. Also the factions on the map are all homebrew (to be potentially changed) sporting up to 4 mojave-sun exclusive themed ones, all based and themed around the shops they occupy in their land.

1. The Chicken Men, A fanatical clan of deranged fast-food themed zealots, occupying the eating district of the mall with their cleavers and robust-contraptions. Worshiping the grand chicken man of the pre-war they control the food and water supply of the mall. Any other sources of food are deemed impure to them and extremely heretical.

2. The Elite, Powerful and civilized upper class of the mall, guarding the entrance with an iron fist, enforced with the immense wealth they control and exude, they look down upon the lower factions from their ivory thrones and fancy suits.

3. The Mechanics. They're the big guys in welded-together "power" armor with fucking crazy contraptions like sawblade launchers and shit, controlling the power over what parts of the mall still have it and practically running the necessities of the place. Low numbers but they have the muscle.

4. The Grillers. A large contained group of insane grill-theme raiders, flames and propane guide them in their manifest destiny to restore the world to how it once was.

eagle lakes 1
eagle lakes
eagle lakes 2
eagle lakes 3
eagle lakes 4
eagle lakes 5

### CODE REVIEW

**Comment by Mannybrado** [comment]
dam thats a lot of z level.............. huh so much... .wtf? cant really base a  map off of that tbh... 👎 @ProfessorPopoff @ProfessorPopoff @ProfessorPopoff @ProfessorPopoff

**Comment by ProfessorPopoff** [comment]
Well. Look at that, Ideaguying and actually doing things with your own hands. I applaud you. I'm willing to take this map under our wing, but there are caveats to this. 

1. The map isn't going to be looked at as most as the current two pre-launch maps, not in the near future at least. Further down the line, it could be worked on by more people, including myself perhaps. It's just going to require too many small individual, unique things. While you could technically sprite and code, even map it all in yourself I think it'd be a misallocation of effort. The faster we get our two maps looking clean and the codebase ready to launch, the better. This is a far-off post launch thing.

2.  The Multi-Z is going to look pretty bad. You've seen it yourself, at dropoff you'll notice the other Zs meld together, due to how TG does multi-z. This could maybe be fixed with a blur of some sort- I don't know. I'll talk uomo into showing me the jist of what he was doing with a blur. This was one of the main reasons I was against Dog City ideaguying, but you've **actually** gone and worked on your idea. So I feel compelled to maybe pop my head in and see if we should be doing anything regarding multi-z, so that down the line we don't have to worry about it, and it looks a bit better sooner than later.

Overall, the map looks like a nice outline, obviously isn't not anywhere near done but the general shape is good, and the change of pace and... Well. Introduction of a potential GAMEMODE is something that I don't think a fallout server on ss13 has actually really done. Period. Unless you include the numerous admin endorsed "GAME MODES". The areas are jank, some things are misaligned, and certain things aren't right. They can be ironed out later on as we actually start active development on this map, though. I do have two requests, though.



Bump up the map size to 130x230x6 from 130x299x6. It's not that much of a gain, from 178,620 to 179,400, and you get to spare your fellow map gang from an aneurysm every time they look at it. Second off, Go ahead into SDMM and into your preferences and set your save mode to TGM. This map currently isn't in TGM format, and will cause issues. Save it as TGM, and push it into the PR and we're good to go. I'll probably have to fix this map up in my floor PR after this is merged.

Wall of text concluded.

**Comment by mrpibb4201337** [comment]
Once TG gets smart about multi-z and Mammoth+Drought are at a level that we consider finished I'd definitely be willing to chip in on this. Reminds me of the mall in I think West Point on Project Zomboid, all isolated and shit.

**Comment by TheRealScarHomie** [comment]
yeah its inspired by that, I'll take that advice, even just having it sitting in the repo increases the chances of people working on it tenfold. Something fresh too instead of all the other City style maps we got. Iron it out n all that shiiit. Good stuff.

**Comment by ProfessorPopoff** [comment]
With all that said. It's a good idea, And could be one of the many big changes that happen to Fallout in ss13. I'll go ahead and merge this in.

**Pull request merged**
