### PR TITLE
Drought factory

### PR DESCRIPTION
**Pull request by Mannybrado**
## About The Pull Request
Adds in a new factory location in a previously empty area on drought. Also adds in a new area for this location.

image
image
image

## Why It's Good For The Game
drought map

### CODE REVIEW

**Comment by ProfessorPopoff** [comment]
image
This will probably try to smooth over and look weird from the inside of either building. But isn't the worst, I'd personally change it.

image
This little overhang will need a roof over the pillars, you could just fill the four spaces and it'd look decent.

**Comment by ProfessorPopoff** [comment]
Not to mention that it could be broken through for easy access to the town.

**Comment by ProfessorPopoff** [comment]
Sorry for the delay. I still need you to give the two nubs an overhanging roof to cover up the top of the walls.
image

**Comment by Mannybrado** [comment]
all done

**Pull request merged**
