### PR TITLE
Adds the Vault Town to Mammoth

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
image
image
Shit. Fuck. Looks like you win this round, @ProfessorPopoff.

Anyway, adds the Vault Town to the map. It's kinda rough around the edges right now, a lot of placeholders and such, but it can be refined as we get more assets- and, you know, it actually sorts out a base for one of our major factions.

I know this is gonna have issues, so reviews are welcomed.

## Why It's Good For The Game
Town is a big faction, right? If town is a big faction, it needs a base.

### CODE REVIEW

**Comment by Mannybrado** [comment]
wheres the screenshots buddy!

**Comment by ProfessorPopoff** [comment]
image
image

I'm going to go ahead and give it a quick runthrough and see what I can pick out. Everything looks pretty cool, and from a skimover it's just minor areas that need to be tweaked.

**Comment by Mannybrado** [comment]
main things i dislike is that the isn't a perimeter reinforced wall around everything and the farming area. it should be actual hydroponics, not a magic cave where the plants grow good, its a vault anyways. Also, most of the place is too destroyed to be an actual vault that survived, you'd think they'd maintain at least the fucking walls. everything else tho? cool! looks good doe!

**Comment by ProfessorPopoff** [comment]
> main things i dislike is that the isn't a perimeter reinforced wall around everything and the farming area. it should be actual hydroponics, not a magic cave where the plants grow good, its a vault anyways. Also, most of the place is too destroyed to be an actual vault that survived, you'd think they'd maintain at least the fucking walls. everything else tho? cool! looks good doe!

A completely sealed tryhard perimeter isn't needed. You can't mine through the lighter rock.  Hydroponics is a WYCI to have our own version that isn't aids. For now the dirt plots are a fine standin. Loremaster you need to get up with the times. Because they're not actual vaulties.

**Comment by Mannybrado** [comment]
> > main things i dislike is that the isn't a perimeter reinforced wall around everything and the farming area. it should be actual hydroponics, not a magic cave where the plants grow good, its a vault anyways. Also, most of the place is too destroyed to be an actual vault that survived, you'd think they'd maintain at least the fucking walls. everything else tho? cool! looks good doe!
> 
> A completely sealed tryhard perimeter isn't needed. You can't mine through the lighter rock. Hydroponics is a WYCI to have our own version that isn't aids. For now the dirt plots are a fine standin. Loremaster you need to get up with the times. Because they're not actual vaulties.

the dirt standins function absolutely identically to normal hydroponics. idk bro. and emm.... i thought the entire point was that they were vaulties since we got rid of the other idea (which was basically the exact same thing) but whatever!
and em... mining in isnt what im concerned about. it just looks stupid that there is a vault with wooden walls exposed, or alternatively absolutely nothing... just walls missing for no reason. if you can't mine through the rock then it isn't an issue putting reinforced walls in anyways.

**Comment by ProfessorPopoff** [comment]
>it just looks stupid that there is a vault with wooden walls exposed, or alternatively absolutely nothing... just walls missing for no reason. if you can't mine through the rock then it isn't an issue putting reinforced walls in anyways.

It's supposed to be half torn down, expanded by hand. Wasters have done this. Not everyone is a legendary pre-war tier construction worker, mister metamancer. Do it yourself in game

**Comment by Mannybrado** [comment]
> It's supposed to be half torn down, expanded by hand. Wasters have done this. Not everyone is a legendary pre-war tier construction worker, mister metamancer. Do it yourself in game

OK. Yeah actually? What if? It was actually just not a finished vault. Like they didnt finish building it. @ProfessorPopoff  @EOBGames hello? hello? I am the best ideasguy in the server and I demand some respect here!

**Comment by ProfessorPopoff** [comment]
I have literally never been less interested. Wait until it goes through and do it yourself if you're that triggered by it.

**Comment by ProfessorPopoff** [comment]
image
Oughta turn this into this
image
It looks a bit slicker. 

A bit of missing areas in the following spots

Outer walls: 
image
image
image
image


If there's going to be vault area out in that little cave portion, it might as well be inside as well with the stage.
image

**Comment by EOBGames** [comment]
Ah shit, my lack of checking areas is showing

**Pull request merged**
